export const locationData = [
  { x: 'A Coruña', y: 1200, parent: 'Galicia', color: '#1f77b4' },
  { x: 'Álava', y: 800, parent: 'País Vasco', color: '#aec7e8' },
  { x: 'Albacete', y: 600, parent: 'Castilla-La Mancha', color: '#ff7f0e' },
  { x: 'Alicante', y: 400, parent: 'Comunidad Valenciana', color: '#ffbb78' },
  { x: 'Almería', y: 300, parent: 'Andalucía', color: '#2ca02c' },
  { x: 'Asturias', y: 500, parent: 'Principado de Asturias', color: '#98df8a' },
  { x: 'Ávila', y: 350, parent: 'Castilla y León', color: '#d62728' },
  { x: 'Badajoz', y: 450, parent: 'Extremadura', color: '#ff9896' },
  { x: 'Barcelona', y: 700, parent: 'Cataluña', color: '#9467bd' },
  { x: 'Burgos', y: 600, parent: 'Castilla y León', color: '#d62728' },
  { x: 'Cáceres', y: 500, parent: 'Extremadura', color: '#ff9896' },
  { x: 'Cádiz', y: 400, parent: 'Andalucía', color: '#2ca02c' },
  { x: 'Cantabria', y: 300, parent: 'Cantabria', color: '#1f77b4' },
  { x: 'Castellón', y: 200, parent: 'Comunidad Valenciana', color: '#ffbb78' },
  { x: 'Ciudad Real', y: 100, parent: 'Castilla-La Mancha', color: '#ff7f0e' },
  { x: 'Córdoba', y: 200, parent: 'Andalucía', color: '#2ca02c' },
  { x: 'Cuenca', y: 300, parent: 'Castilla-La Mancha', color: '#ff7f0e' },
  { x: 'Girona', y: 400, parent: 'Cataluña', color: '#9467bd' },
  { x: 'Granada', y: 500, parent: 'Andalucía', color: '#2ca02c' },
  { x: 'Guadalajara', y: 600, parent: 'Castilla-La Mancha', color: '#ff7f0e' },
  { x: 'Guipúzcoa', y: 700, parent: 'País Vasco', color: '#aec7e8' },
  { x: 'Huelva', y: 800, parent: 'Andalucía', color: '#2ca02c' },
  { x: 'Huesca', y: 900, parent: 'Aragón', color: '#7f7f7f' },
  { x: 'Jaén', y: 1000, parent: 'Andalucía', color: '#2ca02c' },
  { x: 'La Rioja', y: 1100, parent: 'La Rioja', color: '#bcbd22' },
  { x: 'Las Palmas', y: 1200, parent: 'Canarias', color: '#17becf' },
  { x: 'León', y: 1300, parent: 'Castilla y León', color: '#d62728' },
  { x: 'Lleida', y: 1400, parent: 'Cataluña', color: '#9467bd' },
  { x: 'Lugo', y: 1500, parent: 'Galicia', color: '#1f77b4' },
  { x: 'Madrid', y: 1600, parent: 'Comunidad de Madrid', color: '#8c564b' },
  { x: 'Málaga', y: 1700, parent: 'Andalucía', color: '#2ca02c' },
  { x: 'Murcia', y: 1800, parent: 'Región de Murcia', color: '#e377c2' },
  { x: 'Navarra', y: 1900, parent: 'Navarra', color: '#dbdb8d' },
  { x: 'Ourense', y: 2000, parent: 'Galicia', color: '#1f77b4' },
  { x: 'Palencia', y: 2100,  parent: 'Castilla y León', color: '#d62728' },
  { x: 'Pontevedra', y: 2200, parent: 'Galicia', color: '#1f77b4' },
  { x: 'Salamanca', y: 2300, parent: 'Castilla y León', color: '#d62728' },
  { x: 'Santa Cruz de Tenerife', y: 2400, parent: 'Canarias', color: '#17becf' },
  { x: 'Segovia', y: 2500, parent: 'Castilla y León', color: '#d62728' },
  { x: 'Sevilla', y: 2600, parent: 'Andalucía', color: '#2ca02c' },
  { x: 'Soria', y: 2700, parent: 'Castilla y León', color: '#d62728' },
  { x: 'Tarragona', y: 2800, parent: 'Cataluña', color: '#9467bd' },
  { x: 'Teruel', y: 2900, parent: 'Aragón', color: '#7f7f7f' },
  { x: 'Toledo', y: 3000, parent: 'Castilla-La Mancha', color: '#ff7f0e' },
  { x: 'Valencia', y: 3100,  parent: 'Comunidad Valenciana', color: '#ffbb78' },
  { x: 'Valladolid', y: 3200, parent: 'Castilla y León', color: '#d62728' },
  { x: 'Vizcaya', y: 3300, parent: 'País Vasco', color: '#aec7e8'},
  { x: 'Zamora', y: 3400, parent: 'Castilla y León', color: '#d62728'},
  { x: 'Zaragoza', y: 3500, parent: 'Aragón', color: '#7f7f7f'},
];
